project:
  type: book
  output-dir: docs
lang: en
lightbox:
  match: auto
  effect: fade
  desc-position: right
  loop: false

book:
  title: "Microbial Community Analysis"
  subtitle: "Bioinformatic tools"
  # cover-image: src/ico/unine_FS_couleur_ENG.svg
  favicon: src/ico/microbial-culture_9851909.png
  back-to-top-navigation: true
  author:
    - name: Corentin Maslard
      degrees: PhD
      email: corentin.maslard@unine.ch
      orcid: 0000-0002-6951-1963
      url: https://cmaslard.xyz
      affiliations: UniNE
      attributes:
        corresponding: true
  date: today
  date-format: long
  abstract:  "Resume of the course"
  chapters:
    - index.qmd
    #- report/0_data_download.qmd
    - report/0a_data_download.qmd
    - report/1_qiime2.qmd
    - report/2_data_importation_amplicon.qmd
    #- report/3_diversity_rarefaction.qmd
    - report/3a_diversity_rarefaction.qmd
    #- report/4_sourcetracker.qmd
    #- report/5_taxonomy.qmd
    #- report/6_metacoder.qmd
    - references.qmd
  search:
    type: overlay
  repo-url: https://github.com/cmaslard/bioinformatic_tools_mcom_analyse
  repo-actions: [source, issue]
  downloads: [pdf]
  sharing: [twitter, facebook, linkedin]
  output-file: the_book_pdf
  sidebar: 
    border: true
    logo: src/ico/unine_FS_couleur_ENG.svg
    collapse-level: 1
  page-footer: 
    border: true
    background: light
    left: 
      - icon: badge-cc-fill
        url: https://creativecommons.org/licenses/by-nc-sa/4.0/
      - text: "Corentin Maslard 2024"
        href: "https://cmaslard.xyz/" 
      
    center:
      - text: "{{< iconify fa6-solid:envelope >}}"
        href: "mailto:maslard.corentin@gmail.com"
        aria-label: "envelope logo for email"
      - text: "{{< iconify fa6-brands:github >}}"
      - icon: github
        href: https://github.com/cmaslard/phd_soybean_2021_2024/
      - text: "{{< iconify fa6-brands:linkedin >}}"
        href: https://www.linkedin.com/in/corentin-maslard
      - text: "{{< iconify fa6-brands square-x-twitter >}}"
        href: https://x.com/cmaslard
      - text: "{{< iconify fa6-brands bluesky >}}"
        href: https://bsky.app/profile/cmaslard.bsky.social
      - text: "{{< iconify fa6-brands:orcid >}}"
        href: "https://orcid.org/0000-0002-6951-1963"
        aria-label: "ORCID logo linking to ORCID account"
      - text: "{{< iconify fa6-brands:researchgate >}}"
        href: "https://www.researchgate.net/profile/Corentin-Maslard"
        aria-label: "ResearchGate logo linking to ResearchGate account"
      - text: "{{< iconify academicons:google-scholar >}}"
        href: https://scholar.google.com/citations?user=TsztyiMAAAAJ&hl
        target: blank
      - text: "{{< iconify academicons:hal >}}"
        href: https://cv.hal.science/corentinmaslard
        aria-label: "HAL account"
      - text: "{{< iconify pepicons-pop:cv >}}"
        href: "https://docs.google.com/document/d/1oCgrdjnAJuVjgocx3F2kmlbJxlqa6uWrSgqm5fWRhpA/edit?usp=sharing"
        aria-label: "CV"
    right:
        <span class="faux-block">Made with <iconify-icon icon="line-md:heart-twotone"></iconify-icon>, <iconify-icon icon="line-md:coffee-twotone-loop"></iconify-icon>, {{< iconify fa6-brands r-project >}} and [Quarto](https://quarto.org/)</span> |
        <span class="faux-block">[View the source at {{< iconify fa6-brands github >}} GitHub](https://github.com/cmaslard/bioinformatic_tools_mcom_analyse)</span>
      
bibliography: [references.bib]

format:
  html:
    grid:
      body-width: 1000px
    code-fold: false
    code-tools: true
    theme: 
      light: [cosmo, src/theme-light.scss]
      dark: [cosmo, src/theme-dark.scss]
    execute:
      echo: true
      warning: false
editor: source
